---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: jazzinjars
    password: jazzinjars
spring:
  cloud:
    config:
      server:
        git:
          #Create a github repo to store and access correctly to src/main/resources/wa-tolls/* properties
          uri: https://github.com/jazzinjars/spring-cloud-config-server-git
          username: jazzinjars
          password: putavalidpassword
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              #Create a github repo to store and access correctly to src/main/resources/wa-tolls-perf/* properties
              uri: https://github.com/jazzinjars/spring-cloud-config-server-git-perf
              search-paths:
                - 'station*'
